config/routes.rb
Rails.application.routes.draw do
  root 'staticpages#index'
  get 'staticpages/index' => 'staticpages#index'

  get 'staticpages/show' => 'staticpages#show'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def index
    
    
    ENV["FlickRaw.api_key"]
    ENV["Flickraw.shared_secret"]
    

    if params[:user]
      photo = flickr.photos.search(:user_id => params[:user])
      first_photo = flickr.photos.getInfo(:photo_id => photo[0].id)
      @photos = FlickRaw.url(first_photo)
    end
    
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/staticpages/index.html.erb
<h2>Enter your user ID:</h2>
<%=form_tag staticpages_index_path, method: :get do %>
<%=text_field_tag :user, params[:user] %>
<%=submit_tag "Search for user photos"%>
<%end%>

<%if @photos %>
    <%= image_tag @photos %>

<%end%>

app/views/staticpages/show.html.erb
<h1>Staticpages#show</h1>
<p>Find me in app/views/staticpages/show.html.erb</p>